AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  trelloSpecificListLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest'
      Runtime: java8
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 15
      Role: 'arn:aws:iam::573623542714:role/service-role/new-joiners-lambda-role'
      Environment:
        Variables:
          quarkus.lambda.handler: trelloSpecificList
          SNS_TOPIC_ARN: !Ref trelloCardsSNS
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt trelloCardsSNS.TopicName

  trelloCardsLambdaInvokeConfig:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: !Ref trelloSpecificListLambda
      Qualifier: "$LATEST"
      MaximumEventAgeInSeconds: 600
      MaximumRetryAttempts: 0
      DestinationConfig:
        OnSuccess:
          Destination: !Ref trelloCardsSNS

  trelloCardsLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest'
      Runtime: java8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 10
      Role: 'arn:aws:iam::573623542714:role/service-role/new-joiners-lambda-role'
      Environment:
        Variables:
          QUARKUS_LAMBDA_HANDLER: trelloCards
          SNS_TOPIC_ARN: !Ref trelloCardsProcessorSNS
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic: !Ref trelloCardsSNS
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt trelloCardsProcessorSNS.TopicName

  trelloCardsProcessorLambdaInvokeConfig:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: !Ref trelloCardsLambda
      Qualifier: "$LATEST"
      MaximumEventAgeInSeconds: 600
      MaximumRetryAttempts: 0
      DestinationConfig:
        OnSuccess:
          Destination: !Ref trelloCardsProcessorSNS

  trelloCardsProcessorLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest'
      Runtime: java8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 10
      Role: 'arn:aws:iam::573623542714:role/service-role/new-joiners-lambda-role'
      Environment:
        Variables:
          QUARKUS_LAMBDA_HANDLER: trelloCardsProcessor
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic: !Ref trelloCardsProcessorSNS

  trelloCardsSNS:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: new-joiners-trello-cards
      Subscription:
        - Endpoint: !GetAtt trelloCardsLambda.Arn
          Protocol: LAMBDA

  trelloCardsProcessorSNS:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: new-joiners-trello-cards-processor
      Subscription:
        - Endpoint: !GetAtt trelloCardsProcessorLambda.Arn
          Protocol: LAMBDA